repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.1
    hooks:
      - id: isort
        language_version: python3.9
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
