# Generated by Django 3.2 on 2022-05-09 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "new"), (2, "complete")], default=1
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("DE", "de"),
                            ("FR", "fr"),
                            ("NL", "nl"),
                            ("PL", "pl"),
                            ("UK", "uk"),
                        ],
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("products", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(choices=[(1, "accepted"), (2, "rejected")]),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("DE", "de"),
                            ("FR", "fr"),
                            ("NL", "nl"),
                            ("PL", "pl"),
                            ("UK", "uk"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="shopping.cart",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="shelves",
            field=models.ManyToManyField(related_name="carts", to="shopping.Shelf"),
        ),
    ]
