# Generated by Django 3.2 on 2022-05-11 01:13

import django.db.models.deletion
from django.db import migrations, models

ORDER_LIMITS = {
    "DE": 1,
    "FR": 2,
    "NL": 3,
    "PL": 4,
    "UK": 5,
    "GLOBAL": 3,
}


def set_order_limits(apps, schema_editor):
    OrderLimit = apps.get_model(
        app_label="shopping",
        model_name="OrderLimit",
    )
    for country, limit in ORDER_LIMITS.items():
        OrderLimit.objects.create(
            region=country,
            daily_limit=limit,
        )


def remove_order_limits(apps, schema_editor):
    OrderLimit = apps.get_model(
        app_label="shopping",
        model_name="OrderLimit",
    )
    OrderLimit.objects.filter(region__in=ORDER_LIMITS.keys()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Country code", max_length=8, unique=True
                    ),
                ),
                (
                    "daily_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily order limit", null=True
                    ),
                ),
                (
                    "used_limit",
                    models.PositiveIntegerField(
                        default=0, help_text="Current usage, reset daily"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="cart",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carts",
                to="shopping.orderlimit",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="shopping.orderlimit",
            ),
        ),
        migrations.RunPython(set_order_limits, remove_order_limits),
    ]
